### ISSUE TITLE
Fever score in eval script

### ISSUE THREAD

**Issue by ishikasingh** [microsoft/Transformer-XH#2]
Do you also calculate Fever score in Evaluator.py along with classification accuracy?

**Comment by henryzhao5852** [comment]
No, we do not include fever score. You need to compute the fever score based on the prediction file.

**Comment by ishikasingh** [comment]
In Evaluator.py, I checked pred_dict, but it only contain labels. Where do I look for the prediction file? Do you save the output somewhere?

**Comment by henryzhao5852** [comment]
Yes, currently Transformer-XH only predict fever labels, for evidence sentence, we directly use the output from GEAR.
