### ISSUE TITLE
Graph processing for new claims in Fever Task

### ISSUE THREAD

**Issue by ishikasingh** [microsoft/Transformer-XH#3]
Can you provide your script for graph processing or some references to reproduce it? I think I can utilize top 5 sentence retrieval from KGAT, but I think there's another step of graph construction after that.
I wanted to run it for some new claim examples.

**Comment by henryzhao5852** [comment]
Thanks for your interest, currently we plan to only release the final graph but not the whole graph processing code.

**Comment by ishikasingh** [comment]
Okay, thanks for the reply.
I was trying to implement it, I can't figure out how do you get the labels for each evidence in the graph input files that you provided. May I ask for some explanation over that?
Thanks

**Comment by henryzhao5852** [comment]
We directly use the sentence retrieval results (including each evidence label) from [this repo](https://github.com/thunlp/KernelGAT), you might need to check that.
