### ISSUE TITLE
The dev result file have only 5904 samples

### ISSUE THREAD

**Issue by nixiaoyu** [microsoft/Transformer-XH#7]
I ran the codes, but I found there are only 5904 samples in hotpot_dev_graph.json as well as in the final results, not the total 7405 samples. What's wrong with it，is there any thing I should change besides default settings?  I read your paper and the result reported in your paper is on the total dev dataset.
I am looking forward to your reply and thank you very much!

**Comment by henryzhao5852** [comment]
Thanks for your interest, the sample data/model only covers the bridge questions that is 5904 questions in dev set.

**Comment by nixiaoyu** [comment]
Okay, thank you very much! But I have seen the results reported in the paper are on the whole dev set, will you release the data/model on the complete dev set later?

**Comment by henryzhao5852** [comment]
As the main focus of Transformer-XH is on bridge questions, we do not plan to release the other components of the Hotpotqa 
submissions (including comparison questions and supporting facts), sorry about the inconvenience.

**Comment by nixiaoyu** [comment]
Oh, I see. Thank you anyway.
