### ISSUE TITLE
issues with apex

### ISSUE THREAD

**Issue by S-Abdelnabi** [microsoft/Transformer-XH#9]
Thanks a lot for providing the code. 

Would someone please give more information on how to install apex properly, and also possibly which  apex version and pytorch version to ise.
 
I followed the steps here: https://github.com/NVIDIA/apex
I am using docker with image: pytorch/pytorch:1.6.0-cuda10.1-cudnn7-devel

Then I installed apex, as in the quick start instructions of apex, using: 
> pip install -v --disable-pip-version-check --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext" ./

and it seems to have been installed successfully. 
Currently, I am facing these issues, when attempting to train on fever (bash fever_train.sh):

1-line 167 from 'transformer-xh/main.py' 
`from apex.optimizers import FP16_Optimizer`,  gives:

> ImportError: cannot import name 'FP16_Optimizer' from 'apex.optimizers'. 

I tried to solve this by doing: `from apex.contrib.optimizers import FP16_Optimizer` instead, based on https://github.com/NVIDIA/apex/issues/593 

2- With the previous fix, I still face an error at line 176:  

> ModuleNotFoundError: No module named 'fused_adam_cuda'

Would someone please point at what I am doing wrong here?

**Comment by henryzhao5852** [comment]
closed, resolved through emails.
